#!/usr/bin/python3


print("$" + str(24 +25))


print("$" + str(23 * 12))


print("$" + str(10 + 0.5))

# problems 1 through 3

# i fiured out how to make it one line

price = int(40)
#
question_four = (price + 5)
#
print ("Number 4: $" + str(question_four))
#
# problem 4^^^^
#
Sales = int(5)

question_five = (Sales - price)

x=( Sales - price)

print ("Number 5: $" + str(question_five))


# The original price was XX. With a sale of XX, your current prince is XX

print (" The original price was $" + str(price) + ". With a sale of $" + str(Sales) + ", your current price is $" + str(x))





